services:
  db:
    container_name: mysql-master
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - py2mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: Chinses_Reference_Population
    volumes:
      - ./mysql:/dataset

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python-env:
    container_name: python-master
    image: python:3.9.18
    networks:
      - py2mysql
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: /bin/sh -c "pip install numpy nibabel SimpleITK mysql-connector-python shutil"


  gate:
    container_name: gate-master
    image: opengatecollaboration/gate
    volumes:
      - .:/APP

networks:
  py2mysql:
    driver: bridge


                      
    
    
