services:
  db:
    container_name: mysql-master
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER : myuser
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    volumes:
      - ./mysql:/dataset


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  python-env:
    container_name: python-master
    image: python:3.9.18
    volumes:
      - ./src:/usr/src/app
    working_dir: /usr/src/app
    # command: ["ls", "/usr/src/app"]
    entrypoint: ["sh", "-c", "pip install --upgrade pip && pip install numpy nibabel SimpleITK mysql-connector-python shutil && python ./src/get_mac/main.py"]
    depends_on:
      - db
      - adminer



  gate:
    container_name: gate-master
    image: opengatecollaboration/gate
    depends_on:
      python-env:
        condition: service_completed_successfully

                      
    
    
